--- #YAML:1.0
name:                Lemonldap-Portal-Standard
version:             3.2.1
abstract:            Perl extension for the Lemonldap SSO system
license:             ~
author:              
    - Eric German <germanlinux@yahoo.fr>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    MIME::Base64:                  0.0
    Net::LDAP:                     0.0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
