#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-Portal-Standard
version:      0.02
version_from: Standard.pm
installdirs:  site
requires:
    Net::LDAP:                     0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
