# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-Portal-Standard
version:      3.2.0
version_from: lib/Lemonldap/Portal/Standard.pm
installdirs:  site
requires:
    MIME::Base64:                  0.0
    Net::LDAP:                     0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
